name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3.1.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Attempt to use cached dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.pythonLocation }}
          .venv/
        key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile.lock') }}-${{ github.actor == 'dependabot' }}
    - name: Install pipenv and dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: pip install pipenv && pipenv install --dev
    - name: Setup environment variables
      run: cp .env.example .env
    - name: Running pytest
      run: pipenv run pytest --color=yes

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3.1.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Attempt to use cached dependencies
      id: cache-python
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.pythonLocation }}
          .venv/
        key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile.lock') }}-${{ github.actor == 'dependabot' }}
    - name: Install pipenv and dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: pip install pipenv && pipenv install --dev
    - name: Setup environment variables
      run: cp .env.example .env
    - name: Getting coverage report
      run: pipenv run coverage run -m pytest && pipenv run coverage xml
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
